on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: test-deploy
      uses: azure/arm-deploy@v1
      with:
        template: ./AzureWireGuard/AzureWireGuard.bicep
        parameters: AzureWireGuard/AzureWireGuard.parameters.json adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}
        additionalArguments: "--what-if --rollback-on-error --what-if-exclude-change-types Create Ignore"
        failOnStdErr: true

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        template: ./AzureWireGuard/AzureWireGuard.bicep
        parameters: AzureWireGuard/AzureWireGuard.parameters.json adminUsername=${{ secrets.ADMINUSERNAME }} adminPassword=${{ secrets.ADMINPASSWORD }}
        failOnStdErr: false
